env:
  global:
    - CC_TEST_REPORTER_ID=895f73e5c9a7bb819bafb06c10421a32c1d82211df27cf234658a5e7552fe32c
  jobs:
    - TEST_SUITE="~@performance"
    - TEST_SUITE="@performance"

language: ruby

os: linux

rvm:
  - 2.7.0

before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter

install:
  - gem install bundler -v 2.1.0
  - bundle

before_script:
  - if [[ "$TEST_SUITE" == "~@performance" ]]; then ./cc-test-reporter before-build; fi

script:
  - bundle exec rspec --tag $TEST_SUITE

after_script:
  - if [[ "$TEST_SUITE" == "~@performance" ]]; then ./cc-test-reporter after-build -t simplecov --exit-code $TRAVIS_TEST_RESULT; fi
